# agent/state_machine.py

INIT = "INIT"
COLLECT_PROFILE = "COLLECT_PROFILE"
VERIFY_ELIGIBILITY = "VERIFY_ELIGIBILITY"
SCHEME_MATCH = "SCHEME_MATCH"
DOCUMENT_GUIDANCE = "DOCUMENT_GUIDANCE"
END = "END"
